# This script is used to import all strategies to be recognized as subclasses of BrokkrStrategy
# You should import this file where ever you want to reach BrokkrStrategy subclasses
import strategies.brokkr_strategy_A
import strategies.brokkr_strategy_B
import strategies.brokkr_strategy_C
import strategies.brokkr_strategy_B_with_hodl
import strategies.brokkr_strategy_D
import strategies.brokkr_strategy_time_dynamic_ranges
import strategies.brokkr_overlapping_strategy
import strategies.brokkr_strategy_extend_and_decrease
import strategies.invest_all
import strategies.brokkr_strategy_asymmetric
import strategies.brokkr_strategy_partial_rebalance